### PR TITLE
Add VintageNetMobile dependencies

### PR DESCRIPTION
**Pull request by johngiffin**
Adds VintageNetMobile dependencies to nerves_system.

Instructions are documented here: https://github.com/nerves-networking/vintage_net_mobile

Previously tested from fresh Nerves app with Seeed-provided nerves_system_bbb

### CODE REVIEW

**Comment by johngiffin** [comment]
@jeanparpaillon related to the Thingsquare requirement for PPPD.  VintageNetMoble provides a wrapper for PPPD so it may work for setting up the connection for Thingsquare as well.  It uses MuonTrap to manage the daemon.

Example custom config from  testing with the LTE module: 
```
defmodule C2Test.Modem.PPPDConfig do
  @moduledoc false

  alias VintageNetMobile.Chatscript
  alias VintageNet.Interface.RawConfig

  @doc """
  Add the PPPD child specs to the `RawConfig.t()`
  """
  @spec add_child_spec(RawConfig.t(), binary(), non_neg_integer(), keyword()) :: RawConfig.t()
  def add_child_spec(raw_config, serial_port, serial_speed, opts) do
    child_specs = raw_config.child_specs
    priv_dir = Application.app_dir(:vintage_net_mobile, "priv")
    pppd_shim_path = Path.join(priv_dir, "pppd_shim.so")
    pppd_args = make_pppd_args(raw_config.ifname, serial_port, serial_speed, opts)

    env = [{"PRIV_DIR", priv_dir}, {"LD_PRELOAD", pppd_shim_path}]

    pppd_spec = {MuonTrap.Daemon, ["pppd", pppd_args, [env: env]]}

    %RawConfig{raw_config | child_specs: [pppd_spec | child_specs]}
  end

  defp make_pppd_args(ifname, serial_port, serial_speed, opts) do
    cs_path = Chatscript.path(ifname, opts)

    serial_speed = Integer.to_string(serial_speed)

    [
      "connect",
      "chat -v -f #{cs_path}",
      serial_port,
      serial_speed,
      "defaultroute",
      "noipdefault",
      "usepeerdns",
      "persist",
      # "noauth",
      "nodetach",
      "debug",
      "noipdefault",
      "novj",
      "novjccomp",
      "noccp",
      "ipcp-accept-local",
      "ipcp-accept-remote",
      "local",
      "lock",
      "modem",
      "dump",
      "nocrtscts"
    ]
  end
```

**Comment by jeanparpaillon** [comment]
@johngiffin looks interesting. If we can manage sub-ghz network through VintageNet (as a plugin ?), we would probably avoid conflicts in networking configuration

**Review by jeanparpaillon — COMMENTED** [review]
Looks like it's missing vintage_net_mobile dep :)

**Comment by johngiffin** [comment]
> Looks like it's missing vintage_net_mobile dep :)

vintage_net_mobile is only needed as an Aloha dep I believe

**Pull request closed without merging**
